// if exception is not handled then program will terminate abnormally

#include <iostream>

int main() {

    int x = 1;

    try {
        throw x;
    }
    catch(char exception){

    }
    

    return 0;
}